version: '2'
services:
  webapp:
    build: .
    container_name: myapp
    working_dir: /home/app/webapp
    ports:
      - "80:80"
    environment:
      - PASSENGER_APP_ENV=development
    volumes:
      - .:/home/app/webapp
    networks:
      - backend
  db:
    container_name: db
    image: postgres:9.4
    networks:
      - backend
  redis:
    container_name: redis
    image: redis:3.2
    networks:
      - backend
networks:
  backend:
    driver: bridge
