apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: game-ingress
spec:
  rules:
  - host: myapp.gilani.me
    http:
      paths:
      - path:
        backend:
          serviceName: myapp
          servicePort: 80
