development:
  adapter: redis
  url: redis://redis:6379/1
  # adapter: async

test:
  adapter: redis
  url: redis://redis:6379/1
  # adapter: async

production:
  adapter: redis
  url: redis://redis:6379/1
