apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:  # specification of the pod’s contents
      containers:
      - name: myapp
        image: "amingilani/sample-containerized-rails:1.1"
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: secret-key-base
              key: secret.txt
